### ISSUE TITLE
USER STORY RU03- Additional info about charging points (As a first time/returning user I want to be able to see more information about the charging point, so that I can determine if it is appropriate for my needs)

### ISSUE THREAD

**Issue by stef-cruz** [stef-cruz/power-up-point#12]
As a first time/returning user I want to be able to see more information about the charging point, so that I can determine if it is appropriate for my needs

** Acceptance Criteria**
As a user I want to be able to see more information about the charging point

**Assumptions** :  
Data is provided by OpenChargeMap.
The OpenChargeMap embedded map provdes the following information as standard:
* locator point on map
* address
* unique identifier e.g. OCM-15096
* charge type: e.g. Type 2 (Socket Only)
* site type: e.g. (Business Owner at Location)
...Other fields on data card/ info Window

**Tasks**:
 - [x]  Add card with charging point information
 - [x]  Is this enough?  for MVP?  for Delivered_Project?
 - [ ]  is there other information that should also be displayed?  
 - [ ]  Add a Feature to the readme with a brief description of how the user can reach the additional information.

**Comment by DeeMcCart** [comment]
![Image](https://github.com/stef-cruz/power-up-point/assets/126502176/73eb1fd5-b17c-4055-8ea8-92bf24158ad4)
