### ISSUE TITLE
TASK:  Readme first draft

### ISSUE THREAD

**Issue by DeeMcCart** [stef-cruz/power-up-point#53]
**Acceptance Criteria**
First draft of readme produced referencing  PowerUpPoints site as of 08/09/23 14:00

**Tasks**
- [ ] Update deployment link
- [ ] resources, credits
- [ ] Some notes on features (these can be updated by individual contributors tomorrow)
- [ ] Add readme images and links to them (these can be replaced later on if the screens are updated)
- [ ] Get it uploaded as it may be more difficult to find timeslots to merge readme tomorrow with multiple pulls happening
